name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-esp32-gateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build ESP32 Gateway
        working-directory: hardware/firmware/esp32-api-bridge
        run: pio run

  build-gsa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build GSA
        working-directory: hardware/firmware/gerador-sinais-analogicos-GSA
        run: pio run
